# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: EW...another Emotional Wellness blog
name: Austin "Paco" Rainwater
email: rainwater@heckin.io
description: >- # this means to ignore newlines until "baseurl:"
  My personal blog, usually about my journey to emotional wellness,
  sometimes about tech stuff to distract myself from what a difficult 
  journey that is. 
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://ew.heckin.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: pacoawkward
github_username:  pacorain
timezone: America/Chicago

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      read_time: true
      comments: true
      share: false
      related: true


footer:
  links:
    - label: "Open in GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/ew-blog/ew-blog.github.io"   

analytics:
  provider: "google-gtag"
  google:
    tracking_id: "UA-143536634-1"
    anonymize_ip: false # default

search: true
repository: "ew-blog/ew-blog.github.io"
comments:
  provider: "utterances"
  utterances:
    theme: "github-dark" # "github-dark"
    issue_term: "title"
    label: "comment"

permalink: /:categories/:title/

paginate: 5
paginate_path: /page:num/

# Build settings
markdown: kramdown
remote_theme: "mmistakes/minimal-mistakes@4.16.4"
minimal_mistakes_skin: dark
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-include-cache

social:
  type:  Person
  name:  Austin Rainwater
  links:
    - "https://twitter.com/pacoawkward"
    - "https://facebook.com/austindearmond"

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
